# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "NFred224"

# A description of your site for social meta tag, search engines, and feed.xml
description: "NFred224 - A blog and project website for discussions and code regarding Artificial Intelligence, Machine Learning, Deep Learning and Data Science."

# Tagline near the site title
tagline: "Thoughts, stories and ideas."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://nfred224.github.io/"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Projects
  url: /projects/
- text: NF
  url: /NF/
- text: Publications
  url: /publications/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Fred Nilsen"
author_bio: "Fred is an economist, marketer, english scholar, student and future educator with a keen interest in Machine Learning and Data Science."
# author_url:  "http://justgoodthemes.com"
author_location: "Sarpsborg, Norway"
author_image: /images/GoodMorning.jpg

# Sidebar Add banner
banner_url: "https://www.audible.com/"
banner_image: images/audible.png




# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?#u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "NFred224"
facebook_username: "fred.nilsen.127"
#googleplus_username: "+username"
github_username: "NFred224"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
#instagram_username: "username"
#pinterest_username: "username"
#linkedin_username: "username"
#weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
    
exclude: [vendor]
